<!doctype html><html lang=ja><head><meta http-equiv=X-Clacks-Overhead content="GNU Terry Pratchett"><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法 | Shunya Ueta</title>
<meta name=title content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta name=description content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトの Python の実行ランタイムが 2.x 系なのでそれに起因するエラーだった。 pip を Python2 系でおそらくインストールしており、pip21 に更新後は Python3."><meta name=keywords content="python,"><meta property="og:title" content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta property="og:description" content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトの Python の実行ランタイムが 2.x 系なのでそれに起因するエラーだった。 pip を Python2 系でおそらくインストールしており、pip21 に更新後は Python3."><meta property="og:type" content="article"><meta property="og:url" content="https://shunyaueta.com/posts/2021-02-08/"><meta property="og:image" content="https://shunyaueta.com/ogp.jpg"><meta property="article:section" content="posts"><meta property="article:published_time" content="2021-02-08T23:29:12+09:00"><meta property="article:modified_time" content="2021-02-08T23:29:12+09:00"><meta property="og:site_name" content="Shunya Ueta"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://shunyaueta.com/ogp.jpg"><meta name=twitter:title content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta name=twitter:description content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトの Python の実行ランタイムが 2.x 系なのでそれに起因するエラーだった。 pip を Python2 系でおそらくインストールしており、pip21 に更新後は Python3."><meta itemprop=name content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta itemprop=description content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトの Python の実行ランタイムが 2.x 系なのでそれに起因するエラーだった。 pip を Python2 系でおそらくインストールしており、pip21 に更新後は Python3."><meta itemprop=datePublished content="2021-02-08T23:29:12+09:00"><meta itemprop=dateModified content="2021-02-08T23:29:12+09:00"><meta itemprop=wordCount content="93"><meta itemprop=image content="https://shunyaueta.com/ogp.jpg"><meta itemprop=keywords content="python,"><meta name=referrer content="no-referrer-when-downgrade"><style>body{font-family:Verdana,sans-serif;margin:auto;padding:20px;max-width:720px;text-align:left;background-color:#fff;word-wrap:break-word;overflow-wrap:break-word;line-height:1.5;color:#444}h1,h2,h3,h4,h5,h6,strong,b{color:#222}a{color:#3273dc}.title{text-decoration:none;border:0}.title span{font-weight:400}nav a{margin-right:10px}textarea{width:100%;font-size:16px}input{font-size:16px}content{line-height:1.6}table{width:100%}img{max-width:100%}code{padding:2px 5px;background-color:#f2f2f2}pre code{color:#222;display:block;padding:20px;white-space:pre-wrap;font-size:14px;overflow-x:auto}div.highlight pre{background-color:initial;color:initial}div.highlight code{background-color:unset;color:unset}blockquote{border-left:1px solid #999;color:#222;padding-left:20px;font-style:italic}footer{padding:25px;text-align:center}.helptext{color:#777;font-size:small}.errorlist{color:#eba613;font-size:small}ul.blog-posts{list-style-type:none;padding:unset}ul.blog-posts li{display:flex}ul.blog-posts li span{flex:0 0 130px}ul.blog-posts li a:visited{color:#8b6fcb}@media(prefers-color-scheme:dark){body{background-color:#333;color:#ddd}h1,h2,h3,h4,h5,h6,strong,b{color:#eee}a{color:#8cc2dd}code{background-color:#777}pre code{color:#ddd}blockquote{color:#ccc}textarea,input{background-color:#252525;color:#ddd}.helptext{color:#aaa}}</style><script async src="https://www.googletagmanager.com/gtag/js?id=G-JMJRQJT0Q3"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-JMJRQJT0Q3")</script></head><body><header><a href=/ class=title><h2>Shunya Ueta</h2></a><nav><a href=/about/>著者について</a>
<a href=/index.xml>RSS</a></nav></header><main><h1>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法</h1><p><i><time datetime=2021-02-08 pubdate>2021-02-08</time></i></p><content><p>新しいマシンで<code>pip</code>をセットアップして実行しようとすると</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash><span style=display:flex><span>&gt;&gt; pip
</span></span><span style=display:flex><span>Traceback <span style=color:#f92672>(</span>most recent call last<span style=color:#f92672>)</span>:
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/usr/local/bin/pip&#34;</span>, line 11, in &lt;module&gt;
</span></span><span style=display:flex><span>    load_entry_point<span style=color:#f92672>(</span><span style=color:#e6db74>&#39;pip==21.0&#39;</span>, <span style=color:#e6db74>&#39;console_scripts&#39;</span>, <span style=color:#e6db74>&#39;pip&#39;</span><span style=color:#f92672>)()</span>
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 489, in load_entry_point
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>return</span> get_distribution<span style=color:#f92672>(</span>dist<span style=color:#f92672>)</span>.load_entry_point<span style=color:#f92672>(</span>group, name<span style=color:#f92672>)</span>
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2843, in load_entry_point
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>return</span> ep.load<span style=color:#f92672>()</span>
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2434, in load
</span></span><span style=display:flex><span>    <span style=color:#66d9ef>return</span> self.resolve<span style=color:#f92672>()</span>
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2440, in resolve
</span></span><span style=display:flex><span>    module <span style=color:#f92672>=</span> __import__<span style=color:#f92672>(</span>self.module_name, fromlist<span style=color:#f92672>=[</span><span style=color:#e6db74>&#39;__name__&#39;</span><span style=color:#f92672>]</span>, level<span style=color:#f92672>=</span>0<span style=color:#f92672>)</span>
</span></span><span style=display:flex><span>  File <span style=color:#e6db74>&#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;</span>, line <span style=color:#ae81ff>60</span>
</span></span><span style=display:flex><span>    sys.stderr.write<span style=color:#f92672>(</span>f<span style=color:#e6db74>&#34;ERROR: {exc}&#34;</span><span style=color:#f92672>)</span>
</span></span></code></pre></div><p>というエラーが出た。</p><p>デフォルトの Python の実行ランタイムが 2.x 系なのでそれに起因するエラーだった。
pip を Python2 系でおそらくインストールしており、pip21 に更新後は Python3.6 からの機能である f-string が利用され始めたことが起因。</p><h2 id=対処方法>対処方法</h2><p>既存の pip を削除した上で、</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash><span style=display:flex><span>curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
</span></span><span style=display:flex><span>python3 get-pip.py
</span></span></code></pre></div><p>で pip が実行できるようになりエラーが解消された</p><h2 id=references>References</h2><ul><li><a href=https://stackoverflow.com/questions/65866417/pip-install-failing-on-python2>pip install failing on python2</a></li></ul></content>---<p>関連しているかもしれない記事</p><ul><li><a href=/posts/2020-12-26/>PythonでApache beam 入門</a></li><li><a href=/posts/2020-09-09/>pandas を使って特定のディレクトリのCSVファイルをすべて連結して一つのCSVファイルを作成</a></li><li><a href=/posts/2020-08-23/>Python の内包表記とジェネレータ式のメモリ使用量比較</a></li><li><a href=/posts/2020-08-04/>AOJの「ITP I」40問をPythonで解いた</a></li><li><a href=/posts/2020-07-25/>How to write the UnitTest with stdin at Pytest</a></li></ul><br>📮 📧 🐏: 記事への<a href="https://docs.google.com/forms/d/e/1FAIpQLScgZVDrjQiKLbQRovfs88oweCITzjtvt1PlgwL14JfWPOrpPQ/viewform?usp=pp_url&entry.838298670=https%3a%2f%2fshunyaueta.com%2fposts%2f2021-02-08%2f">感想</a>のおたよりをおまちしてます。
お気軽にお送りください。
メールアドレス入力があればメールで返信させていただきます。
もちろんお返事を希望せずに単なる感想だけでも大歓迎です。<br><br>このサイトの更新情報を<a href=/index.xml>RSS</a>で配信しています。
お好きなフィードリーダーで購読してみてください。<br><br>このウェブサイトの運営や著者の活動を支援していただける方を募集しています。
もしよろしければ、<a href=https://www.buymeacoffee.com/hurutoriya>Buy Me a Coffee</a> からサポート(投げ銭)していただけると、著者の活動のモチベーションに繋がります✨<br><br><p><a href=https://shunyaueta.com/tags/python/>#python</a></p></main><footer>Made with <a href=https://github.com/janraasch/hugo-bearblog/>Hugo ʕ•ᴥ•ʔ Bear</a></footer></body></html>