<!doctype html><html lang=ja><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=theme-color content="dark"><title>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法 | Shunya Ueta</title><link rel=stylesheet href=/sass/main.min.1a3290acca8b3fc92df85ea9200859476d6c80d59009c89a749300f3ce7a7a67.css><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create','UA-39994406-11','auto');ga('send','pageview');}</script><meta property="og:title" content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta property="og:description" content="新しいマシンでpipをセットアップして実行しようとすると
1 2 3 4 5 6 7 8 9 10 11 12 13 14  >> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys."><meta property="og:type" content="article"><meta property="og:url" content="https://shunyaueta.com/posts/2021-02-08/"><meta property="og:image" content="https://shunyaueta.com/ogp.jpg"><meta property="article:published_time" content="2021-02-08T23:29:12+09:00"><meta property="article:modified_time" content="2021-10-20T23:18:28+09:00"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://shunyaueta.com/ogp.jpg"><meta name=twitter:title content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta name=twitter:description content="新しいマシンでpipをセットアップして実行しようとすると
1 2 3 4 5 6 7 8 9 10 11 12 13 14  >> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys."></head><body class=dark><nav class=navbar><div class=container><div class=flex><div><a class=brand href=/><span class=emoji>🦅</span>
Shunya Ueta</a></div><div class=flex><a href=/articles/>All posts</a>
<button id=dark-mode-button></button></div></div></div></nav><main><div class=container><article><header class=article-header><div class=thumb><div><h1>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法</h1><div class=post-meta><div>By on <time>2021.02.08</time> (Last updated:<time>2021.10.20</time>)</div><div class=tags><a href=/tags/python/>python</a></div></div></div></div></header></article><div class=article-post><p>新しいマシンで<code>pip</code>をセットアップして実行しようとすると</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt> 1
</span><span class=lnt> 2
</span><span class=lnt> 3
</span><span class=lnt> 4
</span><span class=lnt> 5
</span><span class=lnt> 6
</span><span class=lnt> 7
</span><span class=lnt> 8
</span><span class=lnt> 9
</span><span class=lnt>10
</span><span class=lnt>11
</span><span class=lnt>12
</span><span class=lnt>13
</span><span class=lnt>14
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-bash data-lang=bash>&gt;&gt; pip
Traceback <span class=o>(</span>most recent call last<span class=o>)</span>:
  File <span class=s2>&#34;/usr/local/bin/pip&#34;</span>, line 11, in &lt;module&gt;
    load_entry_point<span class=o>(</span><span class=s1>&#39;pip==21.0&#39;</span>, <span class=s1>&#39;console_scripts&#39;</span>, <span class=s1>&#39;pip&#39;</span><span class=o>)()</span>
  File <span class=s2>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 489, in load_entry_point
    <span class=k>return</span> get_distribution<span class=o>(</span>dist<span class=o>)</span>.load_entry_point<span class=o>(</span>group, name<span class=o>)</span>
  File <span class=s2>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2843, in load_entry_point
    <span class=k>return</span> ep.load<span class=o>()</span>
  File <span class=s2>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2434, in load
    <span class=k>return</span> self.resolve<span class=o>()</span>
  File <span class=s2>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2440, in resolve
    <span class=nv>module</span> <span class=o>=</span> __import__<span class=o>(</span>self.module_name, <span class=nv>fromlist</span><span class=o>=[</span><span class=s1>&#39;__name__&#39;</span><span class=o>]</span>, <span class=nv>level</span><span class=o>=</span>0<span class=o>)</span>
  File <span class=s2>&#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;</span>, line <span class=m>60</span>
    sys.stderr.write<span class=o>(</span>f<span class=s2>&#34;ERROR: {exc}&#34;</span><span class=o>)</span>
</code></pre></td></tr></table></div></div><p>というエラーが出た。</p><p>デフォルトのPython の実行ランタイムが2.x 系なのでそれに起因するエラーだった。
pipをPython2系でおそらくインストールしており、pip21に更新後はPython3.6 からの機能であるf-stringが利用され始めたことが起因。</p><h2 id=対処方法>対処方法</h2><p>既存のpipを削除した上で、</p><div class=highlight><div class=chroma><table class=lntable><tr><td class=lntd><pre class=chroma><code><span class=lnt>1
</span><span class=lnt>2
</span></code></pre></td><td class=lntd><pre class=chroma><code class=language-bash data-lang=bash>curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
</code></pre></td></tr></table></div></div><p>でpipが実行できるようになりエラーが解消された</p><h2 id=appendix>Appendix</h2><ul><li><a href=https://stackoverflow.com/questions/65866417/pip-install-failing-on-python2>pip install failing on python2</a></li></ul></div><h2>See Also</h2><ul><li><a href=/posts/2020-12-26/>PythonでApache beam 入門</a></li><li><a href=/posts/2020-09-09/>pandas を使って特定のディレクトリのCSVファイルをすべて連結して一つのCSVファイルを作成</a></li><li><a href=/posts/2020-08-23/>Python の内包表記とジェネレータ式のメモリ使用量比較</a></li><li><a href=/posts/2020-08-04/>AOJの「ITP I」40問をPythonで解いた</a></li><li><a href=/posts/2020-07-25/>How to write the UnitTest with stdin at Pytest</a></li></ul></div><div class=container><nav class="flex container suggested"><a rel=prev href=/posts/2021-01-17/ title="Previous post (older)"><span>Previous</span>
[抄訳] Towards ML Engineering: A Brief History Of TensorFlow Extended (TFX)</a>
<a rel=next href=/posts/2021-02-09/ title="Next post (newer)"><span>Next</span>
Standard SQLで 列と列の組み合わせの数を集計したい</a></nav></div></main></main><footer class="footer flex"><section class=container><nav class=footer-links><a href=/index.xml>RSS</a></nav></section><script async src=/js/features.min.a94f58a30ad2560de728e080d87f75c60cf806fd1b3d5f4815f1a1a02c0d1859.js></script></footer></body></html>