<!doctype html><html><head><script data-ad-client=ca-pub-8604812913439531 async src=https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><title>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法 - hurutoriya</title><meta name=viewport content="width=device-width,initial-scale=1"><meta property="og:image" content><meta property="og:title" content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta property="og:description" content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトのPython の実行ランタイムが2.x 系なのでそれに起因するエラーだった。 pipをPython2系でおそらくインストールしており、pip21に更新後はPython3.6 からの機能であるf-stringが利用され始めたことが起因。
対処方法 既存のpipを削除した上で、
curl https://bootstrap.pypa.io/get-pip.py -o get-pip."><meta property="og:type" content="article"><meta property="og:url" content="https://shunyaueta.com/posts/2021-02-08/"><meta property="article:published_time" content="2021-02-08T23:29:12+09:00"><meta property="article:modified_time" content="2021-02-08T23:29:12+09:00"><meta name=twitter:card content="summary"><meta name=twitter:title content="pip 実行時に sys.stderr.write(f&#34;ERROR: {exc} &#34;) とエラーが出てpipを実行できないときの対処方法"><meta name=twitter:description content="新しいマシンでpipをセットアップして実行しようとすると
>> pip Traceback (most recent call last): File &#34;/usr/local/bin/pip&#34;, line 11, in <module> load_entry_point('pip==21.0', 'console_scripts', 'pip')() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 489, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2843, in load_entry_point return ep.load() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2434, in load return self.resolve() File &#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;, line 2440, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File &#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;, line 60 sys.stderr.write(f&#34;ERROR: {exc}&#34;) というエラーが出た。
デフォルトのPython の実行ランタイムが2.x 系なのでそれに起因するエラーだった。 pipをPython2系でおそらくインストールしており、pip21に更新後はPython3.6 からの機能であるf-stringが利用され始めたことが起因。
対処方法 既存のpipを削除した上で、
curl https://bootstrap.pypa.io/get-pip.py -o get-pip."><script src=https://shunyaueta.com/js/feather.min.js></script><link href=https://shunyaueta.com/css/fonts.css rel=stylesheet><link rel=stylesheet type=text/css media=screen href=https://shunyaueta.com/css/main.css><link rel=stylesheet type=text/css href=https://shunyaueta.com/css/dark.css media="(prefers-color-scheme: dark)"><script async src="https://www.googletagmanager.com/gtag/js?id=UA-39994406-11"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());gtag('config','UA-39994406-11');</script></head><body><div class=content><header><div class=main><a href=https://shunyaueta.com/>hurutoriya</a></div><nav><a href=/>Home</a>
<a href=/posts>All posts</a>
<a href=/about>About</a>
<a href=/tags>Tags</a></nav></header><main><article><div class=title><h1 class=title>pip 実行時に sys.stderr.write(f"ERROR: {exc} ") とエラーが出てpipを実行できないときの対処方法</h1><div class=meta>Posted on Feb 8, 2021</div></div><section class=body><p>新しいマシンで<code>pip</code>をセットアップして実行しようとすると</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash>&gt;&gt; pip
Traceback <span style=color:#f92672>(</span>most recent call last<span style=color:#f92672>)</span>:
  File <span style=color:#e6db74>&#34;/usr/local/bin/pip&#34;</span>, line 11, in &lt;module&gt;
    load_entry_point<span style=color:#f92672>(</span><span style=color:#e6db74>&#39;pip==21.0&#39;</span>, <span style=color:#e6db74>&#39;console_scripts&#39;</span>, <span style=color:#e6db74>&#39;pip&#39;</span><span style=color:#f92672>)()</span>
  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 489, in load_entry_point
    <span style=color:#66d9ef>return</span> get_distribution<span style=color:#f92672>(</span>dist<span style=color:#f92672>)</span>.load_entry_point<span style=color:#f92672>(</span>group, name<span style=color:#f92672>)</span>
  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2843, in load_entry_point
    <span style=color:#66d9ef>return</span> ep.load<span style=color:#f92672>()</span>
  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2434, in load
    <span style=color:#66d9ef>return</span> self.resolve<span style=color:#f92672>()</span>
  File <span style=color:#e6db74>&#34;/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py&#34;</span>, line 2440, in resolve
    module <span style=color:#f92672>=</span> __import__<span style=color:#f92672>(</span>self.module_name, fromlist<span style=color:#f92672>=[</span><span style=color:#e6db74>&#39;__name__&#39;</span><span style=color:#f92672>]</span>, level<span style=color:#f92672>=</span>0<span style=color:#f92672>)</span>
  File <span style=color:#e6db74>&#34;/Library/Python/2.7/site-packages/pip-21.0-py2.7.egg/pip/_internal/cli/main.py&#34;</span>, line <span style=color:#ae81ff>60</span>
    sys.stderr.write<span style=color:#f92672>(</span>f<span style=color:#e6db74>&#34;ERROR: {exc}&#34;</span><span style=color:#f92672>)</span>
</code></pre></div><p>というエラーが出た。</p><p>デフォルトのPython の実行ランタイムが2.x 系なのでそれに起因するエラーだった。
pipをPython2系でおそらくインストールしており、pip21に更新後はPython3.6 からの機能であるf-stringが利用され始めたことが起因。</p><h2 id=対処方法>対処方法</h2><p>既存のpipを削除した上で、</p><div class=highlight><pre style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash>curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
</code></pre></div><p>でpipが実行できるようになりエラーが解消された</p><h2 id=appendix>Appendix</h2><ul><li><a href=https://stackoverflow.com/questions/65866417/pip-install-failing-on-python2>pip install failing on python2</a></li></ul></section><div class=post-tags><nav class="nav tags"><ul class=tags><li><a href=/tags/python>Python</a></li></ul></nav></div></article></main><h3>See Also</h3><ul><li><a href=/posts/2020-12-26/>Apache beam 入門</a></li><li><a href=/posts/2020-09-09/>pandas を使って特定のディレクトリのCSVファイルをすべて連結して一つのCSVファイルを作成</a></li><li><a href=/posts/2020-08-23/>Python の内包表記とジェネレータ式のメモリ使用量比較</a></li><li><a href=/posts/2020-07-25/>How to write the UnitTest with stdin at Pytest</a></li><li><a href=/posts/2020-05-10/>自走プログラマーを読み終えた</a></li></ul><footer><hr><a class=soc href=https://github.com/hurutoriya title=GitHub><i data-feather=github></i></a>|<a class=soc href=https://twitter.com/hurutoriya/ title=Twitter><i data-feather=twitter></i></a>|⚡️
2021 © Shunya Ueta | <a href=https://github.com/athul/archie>Archie Theme</a> | Built with <a href=https://gohugo.io>Hugo</a></footer><script>feather.replace()</script></div></body></html>